# Author: Erik Martin-Dorel, 2020

# Design:
# - docker-keeper: Lint python scripts (Use flake8)
# - On push for all branches:
#   - Lint images.yml (Use cytopia/yamllint)
#   - Read images.yml (Use pyyaml)
#   - Compute the list of images tags foreach item and store it as artifact
#   - Check that these images tags are disjoint
# - Compute the list of Dockerfiles and store it as artifact
#   - Lint the Dockerfiles (mentioned in generated/Dockerfiles.txt)
#   - Gen README.md as artifact (Supported tags and respective Dockerfile links)
#     (cf. https://hub.docker.com/_/debian/) (with GitLab hyperlinks)
#   - Get the list of remote tags and store it as artifact
#   - Compute the symmetric difference of tags and store it as artifact
# - On push for master (protected branch):
#   - Foreach Dockerfile spec from images.yml (following the list order):
#     - If one of the associated tags does not exists, or with a --rebuild flag:
#       - Run 1 job per Dockerfile spec
#       - Push the image to Docker Hub foreach required tag
#   - Document how to Remove the old tags from Docker Hub
#     (see also https://github.com/docker/roadmap/issues/115)
#   - Document how to Update the README.md
#     - Upload URL: https://hub.docker.com/repository/docker/user/repo
#     - Download URL:
#       - $CI_JOB_URL = https://gitlab.com/coq/coq/-/jobs/$CI_JOB_ID
#       - $CI_JOB_URL/artifacts/file/generated/README.md
#       - $CI_JOB_URL/artifacts/raw/generated/README.md?inline=false
# - [TODO] On scheduled pipelines for master:
#   - Run relevant jobs above (alpha releases | dev -> nightly build)
#   - Run verification that the docker-make subtree is up-to-date (once a day)
# - [TODO] On manual pipelines:
#   - Run relevant jobs for master (taking account --rebuild or so flags)
#   - TODO Document the procedure to rebuild images
#
# - [TODO] documentation to update docker-keeper using git-subtree
# - [TODO] documentation suggesting Dockerfile sources
#
# - [TODO] docker-base & docker-coq: CONTRIBUTE.md → GitHub PRs
# - [TODO] docker-keeper-demo: MWE
# - [TODO] docker-keeper-template: 'active: false', READMEs, link to MWE

include: 'external/docker-keeper/gitlab-ci-template.yml'

# Uncomment if ever you chose a different subtree prefix
# variables:
#   KEEPER_SUBTREE: external/docker-keeper
